### PR TITLE
Made vuestic file structure flatten

### LINKED ISSUE #958: Update Vuestic-UI file structure
Make folder flatter.

image

### PR DESCRIPTION
**Pull request by m0ksem**
## Description
closes #958

Better merge this PR after other pull requests are merged to develop.

THIS PR is REQUIRED for https://github.com/epicmaxco/vuestic-ui/pull/954

I split them into two different PR for better readability.

### CODE REVIEW

**Comment by asvae** [comment]
@m0ksem can you add some explanation on what is done?
Mb folder structure before/after?

**Comment by m0ksem** [comment]
Nw file structure:
```
📦src
 ┣ 📂assets
 ┣ 📂components
 ┃ ┣ 📂va-accordion
 ┃ ┣ 📂va-affix
 ┃ ┣ 📂va-alert
 ┃ ┣ 📂va-app-bar
 ┃ ┣ 📂va-avatar
 ┃ ┣ 📂va-backtop
 ┃ ┣ 📂va-badge
 ┃ .....
 ┣ 📂composables
 ┣ 📂data
 ┣ 📂mixins
 ┃ ┣ 📂ClickOutsideMixin
 ┃ ┣ 📂FormComponent
 ┃ ┣ 📂IconMixin
 ┃ ┣ 📂LoadingMixin
 ┃ ┣ 📂RouterLinkMixin
 ┃ ┣ 📂ScrollMixin
 ┃ ┣ 📂SelectableList
 ┃ ┣ 📂SelectableMixin
 ┃ ┣ 📂StatefulMixin
 ┣ 📂services
 ┃ ┣ 📂api-docs
 ┃ ┣ 📂color-config
 ┃ ┣ 📂component-config
 ┃ ┣ 📂config-transport
 ┃ ┣ 📂global-config
 ┃ ┣ 📂icon-config
 ┣ 📂styles
 ┃ ┣ 📂global
 ┃ ┣ 📂grid
 ┃ ┣ 📂resources
 ┣ 📂types
 ┣ 📂utils
 ┣ 📂vue-book
 ┃ ┣ 📂assets
 ┃ ┣ 📂vuestic-config
 ┣ 📂vuestic-plugin
```

**Comment by m0ksem** [comment]
Also, this PR should remove `packages/ui/src/services/api-docs`. This should be in the docs package.

**Review by asvae — APPROVED** [review]
You have my blessing!

**Pull request merged**
