### PR TITLE
chore(docs): added missing props translations

### LINKED ISSUE #2095: Add missing props description
- [ ] Add missing description
- [ ] _Optional_: add missing examples

**Subject**:
Some `props` descriptions are missing - for example [Input date](https://vuestic.dev/en/ui-elements/date-input#api):
missingPropsDescription

Check other similar cases as well.

Would be great to have additional examples of less intuitive `props`, but this is optional.

### PR DESCRIPTION
**Pull request by xiongmao86**
Try to fix #2095.

## Description
waiting for `file` of `VaFileUpload`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by xiongmao86** [comment]
Hi, I am filling prop descriptions, I meet `contain` in `VaCarousel`, I have difficulty figure out what it means, I have search the whole project with `contain` keyword, but could not find similar component use it, and no similar props in `en.json`.

What does this prop do?

**Comment by xiongmao86** [comment]
Oh, It's in the `VaImage` component. I neglect to check that. Sorry.

**Comment by xiongmao86** [comment]
Adding `aria-select-all-rows-label` to `VaDataTable` emit an `500` error `Body is unusable`. I don't know how to handle this. Can I have review now and postpone the rest work?

**Comment by m0ksem** [comment]
> Hi, I am filling prop descriptions, I meet `contain` in `VaCarousel`, I have difficulty figure out what it means, I have search the whole project with `contain` keyword, but could not find similar component use it, and no similar props in `en.json`.
> 
> What does this prop do?

Looks like contain is an old prop used and `fit="contain"` must be used instead. This prop can be removed in 1.7.0, but not now for compatibility support with old versions. Would be nice to hide this prop from docs.

**Comment by xiongmao86** [comment]
Hi, @m0ksem, thanks for taking the review. As you said `contain` is likely to be deprecated, how can I hide it, do you mean remove it from the `en.json` file?

**Comment by m0ksem** [comment]
> Adding `aria-select-all-rows-label` to `VaDataTable` emit an `500` error `Body is unusable`. I don't know how to handle this. Can I have review now and postpone the rest work?

Can you push changes, so I can take a look? I'm not understanding the issue...

**Comment by m0ksem** [comment]
> Hi, @m0ksem, thanks for taking the review. As you said `contain` is likely to be deprecated, how can I hide it, do you mean remove it from the `en.json` file?

Can be made in api-options.ts file

```ts
export default defineManualApi({
  props: {
    contain: {
      hidden: true,
    }
  },
  // ...
});
```

**Review by m0ksem — APPROVED** [review]
Thanks! Looks good for me.

**Comment by xiongmao86** [comment]
> > Adding `aria-select-all-rows-label` to `VaDataTable` emit an `500` error `Body is unusable`. I don't know how to handle this. Can I have review now and postpone the rest work?
> 
> Can you push changes, so I can take a look? I'm not understanding the issue...

Thank you very much, I'll put it in a new issue.

**Comment by m0ksem** [comment]
> @m0ksem, the issue disappear when I save the edit and then `yarn serve:docs`, it's a work around. I am very sorry for the inconvenient I cause. Should I report an issue? Is appropriate to continue the review and I'll put the rest work on another pr? Or should I continue in the current pr?

I think it is a nuxt issue. If you're able to make reproduction I'd recommend go make issue, but I think it was one-time event. Something related to memory or cache maybe. So just ignore it.

**Comment by xiongmao86** [comment]
Thank you very much, @m0ksem.

**Comment by xiongmao86** [comment]
Hi, @m0ksem, I have proceed to `VaDateInput` component, and I find nothing when I search the repo with `ariaSelectedDateLabel`, it doesn't seem to be used?

**Comment by m0ksem** [comment]
> Hi, @m0ksem, I have proceed to `VaDateInput` component, and I find nothing when I search the repo with `ariaSelectedDateLabel`, it doesn't seem to be used?

Thanks! It is a bug. Prop must be used in `inputAttributesComputed` instead of `tp('selectedDate')`

```
ariaLabel: props.label || tp('selectedDate'),

ariaLabel: props.label || tp(props.ariaSelectedDateLabel),
```

**Comment by m0ksem** [comment]
@xiongmao86, I'm not able to assign you to https://github.com/epicmaxco/vuestic-ui/issues/2095. Can you please write a comment to the issue, so I can assign it to you?

**Comment by xiongmao86** [comment]
Hi, @m0ksem, I have been working on the FileUpload ui component, I have found this `file` prop, It seems belong to the item of `vaFileUploadList`, but not `VaFileUploadList` itself. I wonder why it's exposed at `FileUpload` component? What does it use for?

**Comment by xiongmao86** [comment]
This pr is ready for review, thanks.

**Comment by m0ksem** [comment]
> Hi, @m0ksem, I have been working on the FileUpload ui component, I have found this `file` prop, It seems belong to the item of `vaFileUploadList`, but not `VaFileUploadList` itself. I wonder why it's exposed at `FileUpload` component? What does it use for?

Hi. It is exposed trough `const VaFileUploadListProps = extractComponentProps(VaFileUploadList)`. So VaFileUpload inherit props from VaFileUploadList.

**Review by m0ksem — APPROVED** [review]

**Comment by m0ksem** [comment]
Good work, thanks!

**Comment by xiongmao86** [comment]
> > Hi, @m0ksem, I have been working on the FileUpload ui component, I have found this `file` prop, It seems belong to the item of `vaFileUploadList`, but not `VaFileUploadList` itself. I wonder why it's exposed at `FileUpload` component? What does it use for?
> 
> Hi. It is exposed trough `const VaFileUploadListProps = extractComponentProps(VaFileUploadList)`. So VaFileUpload inherit props from VaFileUploadList.

Ah, What I mean is there are `files` prop, and `file` prop, `files` prop is relate to the `VaFileUploadList`, it represents files to be uploaded. `file` prop is related to the *item* of `VaUploadFileList`, that's only one file, and it represents a file that binds to an item of the `v-for` list of files, but I don't know which file is binded. 

It's strange to have the `file` prop when `files` prop is already there. And pointing to item probably means it shouldn't be exposed as an a prop even in `VaFileUploadList`.

**Pull request merged**
