### PR TITLE
[#2855] Aria attributes hydration fix

### PR DESCRIPTION
**Pull request by aluarius**
Closes: #2855 

## Description
Minor updates and checks of aria attributes keys hydration. Let's use them in kebab case to prevent possible problems in future.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by m0ksem — APPROVED** [review]
We'll forget about it in few days. How about to make some useAriaComposable which accepts only kebab-case attributes. This can be done with TS, so you don't need to take here lodash. Or we can have lodash.kebabCase here for each attribute.

**Review by rustem-nasyrov — APPROVED** [review]
LGTM.

**Comment by aluarius** [comment]
What this composable should do except `useAriaAttributes composable which accepts only kebab-case attributes`? Just checking key names?

**Comment by m0ksem** [comment]
> What this composable should do except `useAriaAttributes composable which accepts only kebab-case attributes`? Just checking key names? Just can't see the way for it to be more useful and stay universal.

Yeah. Something like:
```ts
const useAriaAttributes = <T>(o: ComputedRef<KebabCaseKeys<T>>) => o
```

**Comment by aluarius** [comment]
> Something like

Honestly, can't see any value here, especially because they're pretty static - won't change more then once in a few months. So, changing all correct aria attributes to the composable that is doing the same is pretty weird, but can discuss.

**Comment by m0ksem** [comment]
> > Something like
> 
> Honestly, can't see any value here, especially because they're pretty static - won't change more then once in a few months. So, changing all correct aria attributes to the composable that is doing the same is pretty weird, but can discuss.

This might be helpful for future components, that made by someone who doesn't aware of this issue.

**Pull request merged**
