### PR TITLE
[nuxt-docs] define-page-config plugin

### PR DESCRIPTION
**Pull request by m0ksem**
Highest level of overengineering that human can ever imagine

Basically, here is a plugin-compiler for page-configs. It handles imports from name. I thought it is a good idea, to skip ugly
```
const block = new PageGenerationHelper(__dirname)
```

Then it also skips imports of code examples. Also, code example now is file, so we have syntax highlight in code examples now.

It is easier to write page config now, but much harder to add new block. At first, I thought we can compile page-configs to skip markdown step, but because of locale we need to compile them in runtime(in ssr, but runtime).

I'm thinking to implement runtime blocks, like we had previously. 

I'm thinking about making runtime block generator and make it as auto-import. Then, if it is block.component - compiler will resolve full path to component. This way it will be still easy to add new blocks, but also possible to make some additional pre-compile if needed.

Thanks for the review, @aluarius, now I know where to dig.

closes https://github.com/epicmaxco/vuestic-ui/issues/743 - with nuxt we wouldn't have this stupid caching (it's not working offline btw)
closes https://github.com/epicmaxco/vuestic-ui/pull/2861
closes https://github.com/epicmaxco/vuestic-ui/issues/2852
closes https://github.com/epicmaxco/vuestic-ui/issues/650

TODOS:
- [x] Include fontawesome and iconify fonts
- [ ] VaButtonToggle i18n keys not found
- [ ] Refactor compile to use transform functions inside blocks.
- [ ] Move newer added docs to nuxt docs (like web-components, tailwind and create-vuestic).
- [ ] Use tailwind from CDN (I hope my browser will cache it for outage coding :))) )

### CODE REVIEW

**Comment by m0ksem** [comment]
old docs link https://github.com/epicmaxco/vuestic-ui/tree/10043bd249f38116b9dda0ec789b94cb1643c978

**Comment by m0ksem** [comment]
Partially implements https://github.com/epicmaxco/vuestic-ui/issues/2881

**Comment by m0ksem** [comment]
Added playground component:
image

Should be easy to make and edit them,

**Comment by aluarius** [comment]
1. Some (lots) translations are broken (especially titles). Examples:
- /en/introduction/accessibility-guide#accessibility-guide-examples-keyboard-interactions-title
- /en/getting-started/configuration-guide#configuration-guide-examples-page-config-button-default-title

2. Hash links are totally broken. Example: /en/getting-started/installation#installation-quick-start-title

3. Don't forget about bundle size script.

image

4. Strange code formatter:

image

image

5. Smthng wrong (/en/getting-started/ssr-guide):

image

6. /en/getting-started/kitchensink broken.

7. /en/styles/grid - all example a little bit drunk.

8. In all components no way to return default preset:

image

9. Go here - /en/ui-elements/data-table - and then navigate another page. Content won't change.

10. If page doesn't have meta (title, for example), the last page's title will be shown - it's weird.

11. We should be able to set meta title, meta description and meta robots. I'll be happy to have ability to set `OpenGraph` rich protocol (for beautiful snippets in search results), but it's up to you.

**Comment by m0ksem** [comment]
@aluarius What we do with removing grid? And what's with SmartHelpers? I completely removed Vuestic Grid from Nuxt, so it is in pure tailwind now. I'll need some help here.

**Comment by aluarius** [comment]
> And what's with SmartHelpers?

We won't touch them. They're not conflicting with Tailwind.

> What we do with removing grid?

Ideally,  we should keep them until all grid helpers (except smart ones) will be moved to Tailwind.

**Comment by aluarius** [comment]
No favicon:

image

**Comment by aluarius** [comment]
Minor - incorrect helpers style in search input:

image

**Comment by aluarius** [comment]
Minor, but major for me:

image

My eyes are really bleeding because of this red - can't read without pain.

**Comment by aluarius** [comment]
Minor - wrong gap:

image

**Comment by aluarius** [comment]
/en/introduction/accessibility-guide - missing texts (see https://vuestic.dev/en/introduction/accessibility-guide)

**Comment by rustem-nasyrov** [comment]
Big paddings in mobile version. Code font-size is big. 
image

**Comment by rustem-nasyrov** [comment]
Slider
image

**Pull request merged**
