### PR TITLE
Bundlers test package

### PR DESCRIPTION
**Pull request by m0ksem**
## Description
Yarn workspace package that tests how vuestic-ui runs using vue-cli (webpack) and vite (rollup).

Please, check how it works for you during the review.

I'm not sure if you need to run
```lerna add vuestic-ui``` - should work fine without it. 

If you can not see components after build using `yarn serve:vite` or `yarn serve:webpack`, check out this PR which fixes that issue https://github.com/epicmaxco/vuestic-ui/pull/1029

### CODE REVIEW

**Comment by m0ksem** [comment]
After #1029 build I have such `yarn serve:vite` output (correct):
image

Vue cli output:
image

And tests:
image

**Comment by m0ksem** [comment]
Also, I can not find `vue-cli-service serve` (not dev mode to simulate production server) command for `./dist` and use serve package instead, which is recommended to use in vue docs.

**Comment by m0ksem** [comment]
Tests PR https://github.com/epicmaxco/vuestic-ui/pull/1033 with this feature.

**Comment by asvae** [comment]
Code looks good to me 👍 .

@VasylHryha can you take a look if it works properly, then merge?

**Review by asvae — APPROVED** [review]

**Comment by VasylHryha** [comment]
> 
> 
> Code looks good to me 👍 .
> 
> @VasylHryha can you take a look if it works properly, then merge?

Sure, will check it

**Comment by VasylHryha** [comment]
it works as expected, checked `vite` and `vue-cli`

image

screen from tests

image

**Comment by VasylHryha** [comment]
@m0ksem conflict

**Pull request merged**
