### PR TITLE
fix(sidebar): jump in animation

### PR DESCRIPTION
**Pull request by m0ksem**
Fixing this kind of isse:
https://github.com/epicmaxco/vuestic-ui/assets/23530004/5d65de23-a127-4b1b-9e04-1e2f6e2c7bf6

Need to check if it doesn't introduce other issues.

### CODE REVIEW

**Comment by EugenGedroyc** [comment]
Found a problem: not works [show/hide](https://ui.vuestic.dev/ui-elements/sidebar#v-model) sidebar. I researched this: it needs a "width" property to show/hide.
If menu is completely hidden, there is no "jump in animation"(i checked this in my app)

**Comment by m0ksem** [comment]
> Found a problem: not works [show/hide](https://ui.vuestic.dev/ui-elements/sidebar#v-model) sidebar. I researched this: it needs a "width" property to show/hide. P.S. If menu is completely hidden, there is no "jump in animation". I checked this in my app in in the previous version of vuestic

Yeah. I noticed that this solution cause more problems than fixes.

@EugenGedroyc, Can you check if `vuestic-ui@0.0.0-experimental-a8d2cc1a5-20231129` works Okay in your application?

**Comment by EugenGedroyc** [comment]
@m0ksem yes, the sidebar works fine

**Comment by EugenGedroyc** [comment]
If I click on the close menu button, the menu starts to close but opens again(style="width: 16rem; min-width: 16rem;" - it changes to 0 only after second goes back to 16rem). The menu closes only after the mousedown and thereafter mouseleave events of the closes menu button
Now checked vuestic-ui@0.0.0-experimental-a8d2cc1a5-20231129, everything is still working fine.

**Comment by m0ksem** [comment]
> @m0ksem  If I click on the close menu button, the menu starts to close but opens again(style="width: 16rem; min-width: 16rem;" - it changes to 0 only after second goes back to 16rem). The menu closes only after the mousedown and thereafter mouseleave events of the closes menu button
> Now checked vuestic-ui@0.0.0-experimental-a8d2cc1a5-20231129, everything is still working fine. 
> But is not in 1.8.6 and 1.8.7
> 

Would you be able to reproduce it in ui.vuestic.dev/play?

**Comment by EugenGedroyc** [comment]
@m0ksem This trouble is with prop closeOnClickOutside. 
How can i provide the button from the component layout ? 
`useClickOutside([rootElement, ".va-navbar__left .va-button"]`

**Pull request merged**
