### PR TITLE
Add exports to main package.json

### LINKED ISSUE #1503: Add exports to package.json
Example
```json
  "exports": {
    ".": "./dist/index.mjs",
    "./styles": "./dist/styles/"
  },
```

It's annoying to import `vuestic-ui/dist/styles/essential.css`

should be `vuestic-ui/styles/essential.css`

### PR DESCRIPTION
**Pull request by xiongmao86**
Add exports to package.json so that user can use better imports.

## Description
Add exports so that user of vuestic-ui can make better imports.

fix #1503

## Markup:
Example of using under here.
<details>

```vue
import 'vuestic-ui'  // import ./packages/ui/dist/esm/main.js
require('vuestic-ui') // import ./packages/ui/dist/cjs/main.js

import 'vuestic-ui/ssr' // import ./packages/ui/dist/esm-ssr/main.js
import 'vuestic-ui/iife' // import ./packages/ui/dist/iife/vuestic-ui.js

import 'vuestic-ui/styles/...' // import ./packages/ui/dist/styles/...
import 'vuesttic-ui/types/..' // import ./packages/ui/dist/types/...
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by aluarius** [comment]
@m0ksem may be we want export for vuestic-ui.css as well? `import 'vuestic-ui/vuestic-ui.css'` istead of `import 'vuestic-ui/dist/vuestic-ui.css'`

**Comment by m0ksem** [comment]
> @m0ksem may be we want export for vuestic-ui.css as well? `import 'vuestic-ui/vuestic-ui.css'` instead of `import 'vuestic-ui/dist/vuestic-ui.css'`

Maybe it would be cool even make something like this `import 'vuestic-ui/css'` if it is possible to.

**Comment by xiongmao86** [comment]
Thanks for the tips @aluarius, @m0ksem, I want to make sure that is `vuestic-ui/dist/vuestic-ui.css`, but not `vuestic-ui/packages/ui/dist/vuestic-ui.css`. The latter has `packages/ui` in between.

It's for the user of vuestic-ui, I am not sure the packed code would appear in `vuestic-ui/dist` or like local builds inside `vuestic-ui/packages/ui/dist`.

**Comment by m0ksem** [comment]
> Thanks for the tips @aluarius, @m0ksem, I want to make sure that is `vuestic-ui/dist/vuestic-ui.css`, but not `vuestic-ui/packages/ui/dist/vuestic-ui.css`. The latter has `packages/ui` in between.
> 
> It's for the user of vuestic-ui, I am not sure the packed code would appear in `vuestic-ui/dist` or like local builds inside `vuestic-ui/packages/ui/dist`.

Oh, yes. Didn't even notice. 

We make build in `packages/ui/dist` and publish from `pacakges/ui`, so when user install pacakge he has following structure
```
node_modules
   ...
   vuestic-ui/
      package.json
      dist/
         esm/
         cjs/
         ...
```

We use `packages/*` under development process. It (monorepo) allows us to work in single repository with different npm packages. But on packages/* content provided for npm package.

So paths in `packages/ui/package.json` must be relative to `pacakges/ui` folder, not in root `package.json`.

**Comment by xiongmao86** [comment]
@m0ksem, I guess I should change `package.json` under `package/ui` where `npm publish` happens.

**Comment by xiongmao86** [comment]
Thank you for your help, @m0ksem and @aluarius.

**Pull request merged**
