### PR TITLE
feat(VaTreeView): add cursor style when mouse moves over node

### LINKED ISSUE #3465: VaTreeView: display as cursor style maybe better  when the mouse moves over the tree node
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

VaTreeView:
display as cursor style maybe better when the mouse moves over the tree node.
currently the mouse is the style of the selected text

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by mengqiuleo**
close #3465 

## Description

display as cursor style when the mouse moves over the tree node.
Add `cursor: pointer` to `va-tree-node-root`, then the whole node can have `cursor: pointer`, because class `va-tree-node-root` wrap the whole node. And now can removes the arrow style.

## Markup:

<details>

```css
.va-tree-node {
  &-root {
    // other style
    cursor: pointer;
  }
  // other style
}
```
</details>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by codeonmoon** [comment]
@m0ksem - Could you please let us know when this will be available for usage

**Comment by m0ksem** [comment]
> @m0ksem - Could you please let us know when this will be available for usage

Hi. It will be available in next release after this Friday.

**Comment by codeonmoon** [comment]
@m0ksem - We want to take this change in our project, could you please guide how to use this?

**Comment by m0ksem** [comment]
> @m0ksem - We want to take this change in our project, could you please guide how to use this? I assume it is updating the version in package.json file. As of now my project is on 1.6.5. I can see on this link - [ui.vuestic.dev/ui-elements/tree-view](https://ui.vuestic.dev/ui-elements/tree-view) it is 1.7.1

@codeonmoon, Yeah. You need to update `vuestic-ui` in package.json to 1.7.0 or even better to "^1.7.2" and just run `npm install` (or whatever you use). That should be enought. You might also need to clean `node_modules/.vite/deps` folder to remove changed files.

**Comment by codeonmoon** [comment]
> > @m0ksem - We want to take this change in our project, could you please guide how to use this? I assume it is updating the version in package.json file. As of now my project is on 1.6.5. I can see on this link - [ui.vuestic.dev/ui-elements/tree-view](https://ui.vuestic.dev/ui-elements/tree-view) it is 1.7.1
> 
> @codeonmoon, Yeah. You need to update `vuestic-ui` in package.json to 1.7.0 or even better to "^1.7.2" and just run `npm install` (or whatever you use). That should be enought. You might also need to clean `node_modules/.vite/deps` folder to remove changed files.

@m0ksem I tried following zour instructions here, but I am getting below error now in compile time. The version is 
`"vuestic-ui": "^1.7.2"`
Seems like it is complaining about the import statements. vuestic-ui is being imported as  - 
```
import { createVuestic } from "vuestic-ui";
import "vuestic-ui/css";
```

`**Module not found: Error: Default condition should be last one**`

Could you please assist.

**Comment by m0ksem** [comment]
> > > @m0ksem - We want to take this change in our project, could you please guide how to use this? I assume it is updating the version in package.json file. As of now my project is on 1.6.5. I can see on this link - [ui.vuestic.dev/ui-elements/tree-view](https://ui.vuestic.dev/ui-elements/tree-view) it is 1.7.1
> > 
> > 
> > @codeonmoon, Yeah. You need to update `vuestic-ui` in package.json to 1.7.0 or even better to "^1.7.2" and just run `npm install` (or whatever you use). That should be enought. You might also need to clean `node_modules/.vite/deps` folder to remove changed files.
> 
> @m0ksem I tried following your instructions here, but I am getting below error now in compile time. The version is `"vuestic-ui": "^1.7.2"` Seems like it is complaining about the import statements. vuestic-ui is being imported as -
> 
> ```
> import { createVuestic } from "vuestic-ui";
> import "vuestic-ui/css";
> ```
> 
> `**Module not found: Error: Default condition should be last one**`
> 
> Could you please assist.

Can you try 1.7.0? What's your package manager? Maybe create a discussion instead or visit our Discord, so we don't spam to PR author.

**Pull request merged**
