### PR TITLE
Russian Translation for docs

### LINKED ISSUE #874: Russian translation
Russian locale for Vuestic UI Docs

### PR DESCRIPTION
**Pull request by mxmvshnvsk**
## Description
Russian Translation for docs. Close #874 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by Derranion** [comment]
@mxmvshnvsk Thanks a lot for your job, we are truly appreciate it.

I'll add some changes and merge it when they will be ready.

**Comment by mxmvshnvsk** [comment]
@Derranion, thx u too. I commit some changes soon, pls, check them after that.

**Comment by Derranion** [comment]
@mxmvshnvsk Looks great, well done!

**Review by Derranion — APPROVED** [review]
Ready to merge.

**Pull request merged**
