### PR TITLE
fix(#4132): remove getCurrentInstance from computed

### LINKED ISSUE #4132: getCurrentInstance() warning on console since vuejs upgrade to 3.4.6
**Vuestic-ui version:** 1.8.7

### Description

A warning is shown for avery vuestic component with this message for example:
image

This message is shown since upgrade of vuejs to version 3.4.6

### Reproduction

Juste use any vuestic component.

### PR DESCRIPTION
**Pull request by m0ksem**
closes #4132 

Must be available in 1.8.4

### CODE REVIEW

**Comment by t1m0t** [comment]
Thanks for the fix. Do you have an idea when 1.8.4 will be released?

**Comment by t1m0t** [comment]
> closes #4132
> 
> Must be available in 1.8.4

Thanks for the fix. Do you have an idea when 1.8.4 will be released?

**Comment by m0ksem** [comment]
> > closes #4132
> > Must be available in 1.8.4
> 
> Thanks for the fix. Do you have an idea when 1.8.4 will be released?

@t1m0t, must be available in 1.8.8 right now (not 1.8.4, I misspelled)

**Comment by t1m0t** [comment]
> > > closes #4132
> > > Must be available in 1.8.4
> > 
> > 
> > Thanks for the fix. Do you have an idea when 1.8.4 will be released?
> 
> @t1m0t, must be available in 1.8.8 right now (not 1.8.4, I misspelled)

Upgraded! Thanks for the wonderful work on this package.

**Pull request merged**
