### PR TITLE
[#1290] va select optimization and options slot

### PR DESCRIPTION
**Pull request by aluarius**
close: #1290

## Description
1. Added new bool prop - `longList`. It changes options list rendering from v-if to v-show (no more friezes). Why prop? Because if page will contain lots of select components, it will affect whole page performance.
2. Added new slot for custom options list and related ability to use custom search filtering logic.

Tell your thoughts and then i'll update examples and docs.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by m0ksem** [comment]
How about computed based on options length instead of prop?

**Comment by aluarius** [comment]
> How about computed based on options length instead of prop?

Not sure. We may have friezes because of 1000 textual options or of 100 complex (title+icon+description, for example) as well. And if user will have lags, but have no way to solve them by build-in functional, thats seems not good.

**Comment by Derranion** [comment]
Yeah, I also believe that we want to optimize `options` out of the box.

We could apply `v-show` optimization at a lower `options.length` or just use `v-show` all the time.
To not go deeper into all of this.

We can discuss this tomorrow.

**Review by Derranion — COMMENTED** [review]
Yeah, I also believe that we want to optimize `options` out of the box.

We could apply `v-show` optimization at a lower `options.length` or just use `v-show` all the time.
To not go deeper into all of this.

We can discuss this tomorrow.

**Comment by aluarius** [comment]
I guess this pr make no sense since we've decided to implement virtual scroll. We'll return to this issue after it.

**Pull request closed without merging**
