### PR TITLE
Added code font alert in typography docs

### LINKED ISSUE #1339: Typography code font
.code-snipper uses `Source Code Pro` font and there is no information about it

image

Add this snippet somewhere 
```
<link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet"> 
```

### PR DESCRIPTION
**Pull request by xiongmao86**
## Description
Style sheets uses `Source Code Pro` but didn't import it. This pr import it in `docs/public/index.html`.
fixes #1339

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by asvae** [comment]
Hey. Thanks!

Can't we merge these 2 lines into one? Looks like they're doing pretty much the same? (regular source code pro is actually 400 font weight)

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap">
```

**Comment by xiongmao86** [comment]
Merged two together. I think this would fit in.

**Comment by m0ksem** [comment]
https://github.com/epicmaxco/vuestic-ui/issues/1339 issue is about [Code snippet example](https://vuestic.dev/en/styles/typography#code-snippet). Code snippet uses Source Code Pro font, but it doesn't metioned in docs. Would be nice to have some alert or paragraph "Don't forget to install Source Code Pro font."

**Comment by xiongmao86** [comment]
@m0ksem, do you think adding to `assets installation` of `Manual installation` of `Installation` of `Getting started` fits in?

屏幕截图 2022-04-30 211504

**Comment by m0ksem** [comment]
> @m0ksem, do you think adding to `assets installation` of `Manual installation` of `Installation` of `Getting started` fits in?
> 
> 屏幕截图 2022-04-30 211504

Lets have small alert under this example: https://vuestic.dev/en/styles/typography#code-snippet

Like, you need to install Source Code Pro font (give a code example) if you want to use .code-snippet class.

**Review by m0ksem — APPROVED** [review]

**Pull request merged**
