### PR TITLE
Fix SSR

### PR DESCRIPTION
**Pull request by m0ksem**
## Description
closes https://github.com/epicmaxco/vuestic-ui/issues/798

I have tested vuestic-ui with vite (without ssr) and it's working fine.

But there is a problem with SSR (with vite).

To fix that we need to remove all manipulations with DOM outside vue lifecycle hooks.

### Deprecated components
Also, we need to remove dependencies that depend on DOM API (medium-editor and flatpickr). For that reason, I have deprecated `VaDatePicker` and `VaMediumEditor` components. It's okay because we even don't have documentation pages for this two.

With this PR vuestic runs on SSR + VITE template taken from here:
https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by m0ksem** [comment]
Also. It would be great if we set window and document as possible undefined in eslint.

**Comment by folamy** [comment]
@m0ksem, thank you for your effort on this. 
However, I tried adding vuestic-ui to this
[https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue](url) 
as you have said, but I am still getting this error:

` [vite] Error when evaluating SSR module /src/main.js:
ReferenceError: Element is not defined
    at new VaAppBarProps (webpack-internal:///./node_modules/ts-loader/index.js??clonedRuleSet-4!./node_modules/vue-loader/dist/index.js??ruleSet[0]!./src/components/vuestic-components/va-app-bar/VaAppBar.vue?vue&type=script&lang=ts:16:90)
    at Function._with (webpack-internal:///./node_modules/vue-class-component/dist/vue-class-component.esm-bundler.js:292:23).........`

**Comment by folamy** [comment]
@m0ksem
Can you show me the steps and codes? I am still having issue with the setup.

**Comment by m0ksem** [comment]
> 
> 
> @m0ksem
> Can you show me the steps and codes? I am still having issue with the setup.

@folamy, this Pull Request requires review and has not merged yet. You need to wait until we will make a new release with this feature, sorry.

**Comment by folamy** [comment]
Okay, thank you very much.

**Comment by asvae** [comment]
@m0ksem looks great!

**Comment by folamy** [comment]
@m0ksem.
Please, what's the update on this?

**Comment by m0ksem** [comment]
@folamy, there is [one more issue](https://github.com/epicmaxco/vuestic-ui/issues/821) that we want to fix before the next release for complete Vite support. I hope there will be a new release in a few days.

**Pull request merged**
