### PR TITLE
[#2870] `VaImage` intersectioning

### PR DESCRIPTION
**Pull request by aluarius**
Currently blocked by https://github.com/epicmaxco/vuestic-ui/pull/2868

Closes: #2870

## Description
- [x] use intersection observer composable debugging and refactoring to make in more universal;
- [x] lazy load feature for the va-image component.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by rustem-nasyrov — CHANGES_REQUESTED** [review]
The image loads right after page refresh.

**Comment by m0ksem** [comment]
What's wrong with `loading="lazy"`?

**Comment by aluarius** [comment]
> What's wrong with loading="lazy"?

Answered in Slack.

**Comment by aluarius** [comment]
> The image loads right after page refresh.

Fixed. Had some troubles to make it work well with SSR.

**Review by rustem-nasyrov — APPROVED** [review]

**Comment by m0ksem** [comment]
@aluarius, please double check how it works with nuxt in sandbox and merge it.

**Comment by aluarius** [comment]
I've tested it first of all in Nuxt :)

**Pull request merged**
