### PR TITLE
Transfering docs to Tailwind

### PR DESCRIPTION
**Pull request by aluarius**
Related: #2816 

## Description
- [x] tailwind was added to the docs;
- [x] all margin-padding helpers (mr-1, pt-6 etc) were fixed depending on Tailwind values scale;
- [x] old  margin-padding helpers were commented because of names conflicts;
- [x] tailwind was added to the vue book via cdn stylesheet;
- [x] codesandbox config updated;
- [x] conflicts for `flex` helper resolved.  

**No need to check hundreds of changed files in docs/src, because there're lots of similar changes (mt-4 -> mt-6 etc).**

New values are not identical to old ones, because tailwind uses 4-divisible scale, unlike ours. So, some padding-margins were changed from 12.8px to 12px for example. I've not mentioned any meaningfull artefacts on the site because of this, but better take a look twice.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by m0ksem — COMMENTED** [review]
Don't forget to update condsandbox config, because we use tailwind in code examples. Also, it sucks now that demo can not be simply copy/pasted :(

Let's have same config for vue-book and docs. Might even worth to move it in separate package.

Why gird is commented, but not removed?

**Comment by aluarius** [comment]
> Why gird is commented, but not removed?

Just to be able to return them any moment. We call totally remove them in 1/6/0, i guess. Will add a comment.

**Comment by aluarius** [comment]
> Also, it sucks now that demo can not be simply copy/pasted :(

Don't worry, this helpers were used (for about 90 percents ) in purpose of spacings between different demos :)

**Comment by rustem-nasyrov** [comment]
Missing margins here. 
image

**Comment by rustem-nasyrov** [comment]
image
Margin class didn't apply here.

**Comment by rustem-nasyrov** [comment]
image
image

Missing button color in the landing page.

**Comment by rustem-nasyrov** [comment]
image
Bigger indents then on the vuestic.dev

**Comment by rustem-nasyrov** [comment]
@xx13 is it ok to you if the code fonts will be like this? 
<details>
In the PR:
image
Prod:
image

</details>

**Comment by rustem-nasyrov** [comment]
https://vuestic.dev/en/ui-elements/date-input#mode
<details>
image
</details>

**Comment by rustem-nasyrov** [comment]
Switch.
Same on prod.
<details>
image
</details>

**Comment by rustem-nasyrov** [comment]
Divider.
<details>
image

</details>

**Comment by rustem-nasyrov** [comment]
<details>
<summary>Scroll container</summary>
Horizontal scroll doesn't work.
image

</details>

**Comment by rustem-nasyrov** [comment]
<details>
<summary>Split</summary>
image

</details>

**Comment by xx13** [comment]
prod version with smaller font size looks better


> @xx13 is it ok to you if the code fonts will be like this? 
> 
> <details>
> 
> In the PR:
> 
> image
> 
> Prod:
> 
> image
> 
> 
> 
> </details>

**Comment by aluarius** [comment]
Thanks, @rustem-nasyrov !

All problems listed above (including font issue) were caused by conflicts of reset files (i've disabled Tailwind's one) and `flex` helper (it's really `display: flex` for Tailwind, but `display: block` for Vuestic helpers %).

**Comment by rustem-nasyrov** [comment]
<details>
<summary>Switch</summary>
image
image
</details>

<details>
<summary>Split</summary>
If it's not difficult for you, could you fix it as well?
image
</details>

**Comment by aluarius** [comment]
This (https://user-images.githubusercontent.com/29167241/211571987-9867982e-19bb-40cf-84bb-d46ac337bd7f.png) isn't related to this pr. I know the way to fix it, but awaiting response from Maxim.

**Comment by rustem-nasyrov** [comment]
> This (https://user-images.githubusercontent.com/29167241/211571987-9867982e-19bb-40cf-84bb-d46ac337bd7f.png) isn't related to this pr. I know the way to fix it, but awaiting response from Maxim.

You need to apply `align-items: flex-start` styles and it will be fixed.
image

**Comment by aluarius** [comment]
> You need to apply `align-items: flex-start` styles and it will be fixed

Yea, but it doesn't solve initial bug with the component.

**Comment by aluarius** [comment]
Switch problem moved to https://github.com/epicmaxco/vuestic-ui/issues/2864

**Pull request merged**
