### PR TITLE
fixed warnings about reactive objects in docs

### LINKED ISSUE #898: Docs in dev mode is showing warnings about reactive components.
TODO: provide a screenshot.

For now, you can open any docs page and see a lot of warnings.

### PR DESCRIPTION
**Pull request by sergey-kravcov**
close #898 

## Description
Fixed warnings about reactive objects in doc pages.

It was:
Снимок экрана 2021-06-30 в 17 03 25

Now:
Снимок экрана 2021-06-30 в 17 03 05

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Review by m0ksem — APPROVED** [review]
This PR fixes #869 as I can see.

**Comment by asvae** [comment]
@sergey-kravcov can you explain a bit how that works (in comments)?

**Comment by sergey-kravcov** [comment]
@asva There is a component in the documentation that is responsible for displaying examples of using the components from Vuestick. This component is DocsExample. It not only shows examples of use, but also the example code. Therefore, as a prop, it takes the name of the component of the example. After that, it imports the component itself in the created hook and also reads its code (dividing the code into three parts: template, style, script). To display a component of the example, it must be available for the template of DocsExample, so you need to place it in the variable from `this`. But this variable must not be reactive, otherwise that warning will appear.

**Comment by asvae** [comment]
@sergey-kravcov I see the problem.

you can probably just 'v-if=component' instead of using additional variable

**Comment by sergey-kravcov** [comment]
@asvae The `component` variable is not reactive and does not cause the template to be updated after the component is imported. So I used an additional variable.

**Comment by asvae** [comment]
@sergey-kravcov and why it's not reactive? Maybe you can just use null instead? :P

**Comment by sergey-kravcov** [comment]
@asvae This variable cannot be reactive because warnings will pop up again. I used the shallowRef variable instead of the reactive one and it did the trick.

**Comment by alygee** [comment]
> * [x]  Same thing should be also fixed on landing
>   image

passed raw objects to buttons in footer to avoid these warnings

**Pull request merged**
