### PR TITLE
Docs/fix incorrect imports

### PR DESCRIPTION
**Pull request by m0ksem**
closes https://github.com/epicmaxco/vuestic-ui/issues/3100

Removed imports like `vuestic-ui/src/styles/grid.scss` which are not available for end-user.

### CODE REVIEW

**Comment by m0ksem** [comment]
> Grids should be available for end user until 1.7.0.

They are. I just fixed import paths. I meant to write "changed `vuestic-ui/src/styles/grid.scss` to `vuestic-ui/styles/grid.css`".

**Review by rustem-nasyrov — CHANGES_REQUESTED** [review]
`dev:build` and  `dev:prepare` commands are throwing errors.
image

**Comment by m0ksem** [comment]
> `dev:build` and `dev:prepare` commands are throwing errors. image

Fixed. Also, prefer yarn sandbox:nuxt. Idk why do we need this playground.

**Comment by m0ksem** [comment]
> `dev:build` and `dev:prepare` commands are throwing errors. image

It is not related to this PR. Made another one instead: https://github.com/epicmaxco/vuestic-ui/pull/3113

**Review by rustem-nasyrov — APPROVED** [review]
Build works fine.

**Pull request merged**
